Repository pomazkovanton/liza-alert, pull requests merged in 2022-05, with the labels that each got.

#6 fonts Подключить шрифты к проекту #1
  accets/fonts/Golos-Text_Bold.woff
  accets/fonts/Golos-Text_Bold.woff2
  accets/fonts/Golos-Text_Medium.woff
  accets/fonts/Golos-Text_Medium.woff2
  accets/fonts/Golos-Text_Regular.woff
  accets/fonts/Golos-Text_Regular.woff2
  css/vendor/fonts.css
Labels: feat

#11 :bug: fix: влить изменения в develop #4
  assets/fonts/.gitkeep
  assets/fonts/Golos-Text_Bold.woff
  assets/fonts/Golos-Text_Bold.woff2
  assets/fonts/Golos-Text_Medium.woff
  assets/fonts/Golos-Text_Medium.woff2
  assets/fonts/Golos-Text_Regular.woff
  assets/fonts/Golos-Text_Regular.woff2
  assets/images/.gitkeep
  assets/images/icons.svg
Labels: bug

#13 добавить Css-переменные
  css/vendor/variables.css
  package-lock.json
Labels: feat

#32 удалить лишние файлы CSS
  css/pages/course-finished-sorry.css
  css/pages/index.css
  css/pages/lesson-test-about.css
  css/pages/lesson-test-preview.css
  css/pages/lesson-test.css
  css/pages/lesson-video.css
  css/pages/test-result-fail.css
  css/pages/test-result-success.css
Labels: fix

#33 :lipstick: style: создать стили заголовков
  blocks/title/_size/title_size_l.css
  blocks/title/_size/title_size_m.css
  blocks/title/_size/title_size_s.css
  blocks/title/_type/title_type_error.css
  blocks/title/_type/title_type_success.css
  blocks/title/title.css
  css/pages/index.css
Labels: style

#35 :sparkles: feat: сделать стили контейнеру для карточек #19
  blocks/card-container/__header/card-container__header.css
  blocks/card-container/card-container.css
  css/vendor/variables.css
Labels: style

#38 pull-request: добавить описание проекта #27
  README.md
Labels: documentation

#37 pull-request: добавить стили для блока accordion #22
  assets/images/accordion-arrow.svg
  css/blocks/accordion/__header/accordion__header.css
  css/blocks/accordion/__item/accordion__item.css
  css/blocks/accordion/__list/accordion__list.css
  css/blocks/accordion/accordion.css
  css/pages/index.css
Labels: style

#42 pull-request: сделать блок video #16
  assets/images/icons.svg
  assets/images/video-poster.jpeg
  css/blocks/video/__btn/_type/video__btn_type_fullscreen.css
  css/blocks/video/__btn/_type/video__btn_type_play.css
  css/blocks/video/__btn/_type/video__btn_type_sound.css
  css/blocks/video/__btn/video__btn.css
  css/blocks/video/__controls/video__controls.css
  css/blocks/video/__mediaplayer/video__mediaplayer.css
  css/blocks/video/__slider/_type/video__slider_type_sound.css
  css/blocks/video/__slider/_type/video__slider_type_timeline.css
  css/blocks/video/__slider/video__slider.css
  css/blocks/video/__sound-wrap/video__sound-wrap.css
  css/blocks/video/video.css
  css/pages/index.css
  pages/lesson-video.html
Labels: feat

#41 pull-request: добавить стили для информационного элемента#29
  css/blocks/info-element/__icon/info-element__icon.css
  css/blocks/info-element/_type/info-element_type_success.css
  css/blocks/info-element/_type/info-elemet_type_error.css
  css/blocks/info-element/info-element.css
  css/pages/index.css
Labels: style

#39 pull-request: cделать универсальные стили для блока result #23
  css/blocks/result/__text/result__text.css
  css/blocks/result/__title/result__title.css
  css/blocks/result/_type/result_type_error.css
  css/blocks/result/_type/result_type_success.css
  css/blocks/result/result.css
  css/pages/index.css
  css/vendor/variables.css
Labels: style

#45 Features/css checkboxes#9
  assets/images/checked.svg
  assets/images/empty-focused.svg
  assets/images/empty-hover.svg
  assets/images/empty.svg
  assets/images/radio-checked.svg
  assets/images/radio-empty-focused.svg
  assets/images/radio-empty-hover.svg
  assets/images/radio-empty.svg
  css/blocks/button/__center/button__center.css
  css/blocks/checkbox/__custom/checkbox__custom.css
  css/blocks/checkbox/__input/checkbox__input.css
  css/blocks/checkbox/checkbox.css
  css/blocks/radio/__custom/radio__custom.css
  css/blocks/radio/__input/radio__input.css
  css/blocks/radio/radio.css
  css/blocks/test/__answers/test__answers.css
  css/blocks/test/__block/test__block.css
  css/blocks/test/__line/test__line.css
  css/blocks/test/__link/test__link.css
  css/blocks/test/__question/test__question.css
  css/pages/index.css
  pages/lesson-test.html
Labels: feat

#43 сделать стили для блока link
  css/blocks/link/__icon/_color/link__icon_color_success.css
  css/blocks/link/__icon/link__icon.css
  css/blocks/link/_active/link_active.css
  css/blocks/link/_text/link_text_medium.css
  css/blocks/link/link.css
  css/pages/index.css
  css/vendor/variables.css
Labels: style

#44 pull request: Сделать универсальный блок для сетки #25
  .gitignore
  css/blocks/page/__col-left/page__col-left.css
  css/blocks/page/__col-right/page__col-right.css
  css/blocks/page/__main/page__main.css
  css/blocks/page/page.css
  css/pages/index.css
  pages/course-finished-congratulations.html
  pages/course-finished-sorry.html
  pages/lesson-test-about.html
  pages/lesson-test-preview.html
  pages/lesson-test.html
  pages/test-result-fail.html
  pages/test-result-success.html
Labels: feat, style

#47 pull request: cделать блок с содержанием #24
  css/blocks/nav-lessons/__item/nav-lessons__item.css
  css/blocks/nav-lessons/__list/nav-lessons__list.css
  css/blocks/nav-lessons/nav-lessons.css
  css/pages/index.css
  pages/course-finished-congratulations.html
  pages/course-finished-sorry.html
  pages/lesson-test-about.html
  pages/lesson-test-preview.html
  pages/lesson-test.html
  pages/lesson-video.html
  pages/test-result-fail.html
  pages/test-result-success.html
Labels: feat

#50 pull request: блок Breadcrumb (путь пользователя) #15
  css/blocks/breadcrumb/__current-location/breadcrumb__current-location.css
  css/blocks/breadcrumb/__icon/breadcrumb__icon.css
  css/blocks/breadcrumb/__item/breadcrumb__item.css
  css/blocks/breadcrumb/breadcrumb.css
  css/blocks/page/__content/page__content.css
  css/blocks/page/__main/page__main.css
  css/pages/index.css
  pages/course-finished-congratulations.html
  pages/course-finished-sorry.html
  pages/lesson-test-about.html
  pages/lesson-test-preview.html
  pages/lesson-test.html
  pages/lesson-video.html
  pages/test-result-fail.html
  pages/test-result-success.html
Labels: feat, style

#51 pull request: сделать два блока "Курс завершен" #49
  css/blocks/result/result.css
  pages/course-finished-congratulations.html
  pages/course-finished-sorry.html
Labels: feat

#56 pull-request: добавить блок "О тесте"#28
  assets/images/icons.svg
  css/blocks/about-test/__button/about-test__button.css
  css/blocks/about-test/__info/about-test__info.css
  css/blocks/about-test/__line/about-test__line.css
  css/blocks/about-test/about-test.css
  css/pages/index.css
  pages/lesson-test-about.html
  pages/lesson-test-preview.html
Labels: feat

#57 pull request: Исправить отступы и стили у блока test#48
  css/blocks/checkbox/__custom/checkbox__custom.css
  css/blocks/checkbox/checkbox.css
  css/blocks/radio/__custom/radio__custom.css
  css/blocks/radio/radio.css
  css/blocks/test/__block/test__block.css
  css/blocks/test/__link/test__link.css
  css/blocks/test/__question/test__question.css
  css/pages/index.css
  pages/lesson-test.html
Labels: fix

#65 pull request: заменить иконку "без звука "на более подходящую #63
  assets/images/icons.svg
  pages/lesson-video.html
Labels: feat

#66 pull request: добавить адаптив для блока header #62
  css/blocks/header/__container/header__container.css
  css/blocks/header/__nav-btn/header__nav-btn.css
  css/blocks/header/__nav-ico-cross/_show/header__nav-ico-cross_show.css
  css/blocks/header/__nav-ico-cross/header__nav-ico-cross.css
  css/blocks/header/__nav-ico-menu/_show/header__nav-ico-menu_show.css
  css/blocks/header/__nav-ico-menu/header__nav-ico-menu.css
  css/blocks/header/__nav-item/header__nav-item.css
  css/blocks/header/__nav-list/header__nav-list.css
  css/blocks/header/__nav/_opened/header__nav_opened.css
  css/blocks/header/__nav/header__nav.css
  css/blocks/header/header.css
  css/pages/index.css
  pages/lesson-video.html
  scripts/main.js
Labels: feat

#68 Fix/test form
  css/blocks/checkbox/__input/checkbox__input.css
  css/blocks/checkbox/checkbox.css
  css/blocks/radio/radio.css
  pages/lesson-test.html
Labels: fix

#75 pull request: подключить адаптивный Header на всех страницах #70
  assets/fonts/.gitkeep
  assets/images/.gitkeep
  css/blocks/header/__container/header__container.css
  pages/course-finished-congratulations.html
  pages/course-finished-sorry.html
  pages/lesson-test-about.html
  pages/lesson-test-preview.html
  pages/lesson-test.html
  pages/lesson-video.html
  pages/test-result-fail.html
  pages/test-result-success.html
  scripts/.gitkeep
  scripts/header-nav.js
  scripts/video.js
Labels: feat

#76 pull request: переделать сетку и добавить паддинги #55
  css/blocks/page/__col-left/page__col-left.css
  css/blocks/page/__col-right/page__col-right.css
  css/blocks/page/__content/page__content.css
  css/blocks/page/__main/page__main.css
Labels: fix

#77 pull request: исправить пути до шрифтов #60
  css/vendor/fonts.css
Labels: fix

#78 pull request: сделать секцию с результатом теста #31
  css/blocks/button/__center/button__center.css
  css/blocks/test-info/__answer-item/test-info__answer-item.css
  css/blocks/test-info/__answer-list/test-info__answer-list.css
  css/blocks/test-info/__button/test-info__button.css
  css/blocks/test-info/__header/test-info__header.css
  css/blocks/test-info/__question/test-info__question.css
  css/blocks/test/__line/test__line.css
  css/pages/index.css
  pages/test-result-fail.html
  pages/test-result-success.html
Labels: feat

#80 pull request: создать медиазапросы для элементов с текстом #79
  css/blocks/button/button.css
  css/blocks/info-element/__icon/info-element__icon.css
  css/blocks/info-element/info-element.css
  css/blocks/link/__icon/link__icon.css
  css/blocks/link/link.css
  css/blocks/test/__button/test__button.css
  css/blocks/text/text.css
  css/blocks/title/_size/title_size_l.css
  css/blocks/title/_size/title_size_m.css
  css/blocks/title/_size/title_size_s.css
  css/pages/index.css
  pages/lesson-test.html
Labels: feat

#83 :lipstick: style: уменьшить зазмер чекбоксов / радио кнопок при разре…
  css/blocks/checkbox/__custom/checkbox__custom.css
  css/blocks/radio/__custom/radio__custom.css
Labels: style

#85 pull request: сделать адаптив для блок с кнопками #71
  css/blocks/action-panel/action-panel.css
Labels: style

#72 pull request: исправить адаптив для хлебных крошек #53
  css/blocks/breadcrumb/__icon/breadcrumb__icon.css
  css/blocks/breadcrumb/__item/breadcrumb__item.css
  css/blocks/breadcrumb/__link/breadcrumb__link.css
  css/blocks/breadcrumb/breadcrumb.css
  css/pages/index.css
  pages/course-finished-congratulations.html
  pages/course-finished-sorry.html
  pages/lesson-test-about.html
  pages/lesson-test-preview.html
  pages/lesson-test.html
  pages/lesson-video.html
  pages/test-result-fail.html
  pages/test-result-success.html
Labels: feat, style, refactor

#90 pull request: сделать адаптив для блока test-info #86
  css/blocks/about-test/__line/about-test__line.css
  css/blocks/about-test/__text/about-test__text.css
  css/blocks/action-panel/action-panel.css
  css/pages/index.css
  pages/course-finished-congratulations.html
  pages/course-finished-sorry.html
  pages/lesson-test-about.html
  pages/lesson-test-preview.html
  pages/lesson-test.html
  pages/lesson-video.html
  pages/test-result-fail.html
  pages/test-result-success.html
Labels: feat

#91 pull request: сделать адаптив для блока видео #87
  css/blocks/video/__controls/video__controls.css
  css/blocks/video/__slider/_type/video__slider_type_sound.css
  css/blocks/video/__sound-wrap/video__sound-wrap.css
  css/blocks/video/video.css
Labels: feat

#99 pull request: объединить дублируемые свойства для нескольких селекторов #97
  css/blocks/checkbox/__input/checkbox__input.css
  css/blocks/radio/__input/radio__input.css
Labels: style

#100 pull request: добавить эффект при наведении (:hover) для шапки аккордеона #94
  css/blocks/accordion/__header/accordion__header.css
Labels: fix

#101 pull request: добавить эффект при наведении (:hover) для кнопок #93
  css/blocks/button/_type/button_type_primary.css
  css/blocks/button/_type/button_type_secondary.css
Labels: fix

#102 pull request: заменить span'ы на ссылки (course-finished-sorry.html) #95
  css/blocks/link/_type/link_type_inner.css
  css/blocks/text/_type/text_type_accent.css
  css/pages/index.css
  pages/course-finished-sorry.html
Labels: fix

#98 :bug: fix: добавить кнопкам блока Видео hover эффект.
  css/blocks/video/__btn/video__btn.css
  css/blocks/video/__slider/video__slider.css
Labels: fix
